class GeoLocatorException implements Exception {}

class LocationServiceDisabledGeolocatorException extends GeoLocatorException {}

class LocationPermissionDeniedGeolocatorException extends GeoLocatorException {}

class LocationPermissionDeniedForeverGeolocatorException extends GeoLocatorException {}