class LocationServiceDisabledGeolocatorException implements Exception {}

class LocationPermissionDeniedGeolocatorException implements Exception {}

class LocationPermissionDeniedForeverGeolocatorException implements Exception {}